### PR TITLE
integrate eslint

### LINKED ISSUE #34: Integrate ESLint
We should abide by stronger logic linting rules and dissuade bad practices that lead to code smell as more people contribute to the project.

ESLint integrated with Prettier should cover general bases and improve code quality, while lessening the potential for debates over syntax.

### PR DESCRIPTION
**Pull request by odama626**
fixes #34 

this adds eslint and moves to pretty-quick for prettier, but doesn't enable eslint yet -- want to get some of @tonyketcham's big Prs in first

### CODE REVIEW

**Comment by tonyketcham** [comment]
Looking great!
 
Before this goes in, we should:
- start a branch off of this that runs the formatting
- in that new branch, we can fix all the places ESLint screams about quick and dirty stuff we've done (particularly around types 😛)
  - this will likely take some time and might need both of us to chip away at it to resolve all the errors

Then after this goes in, we can:
- merge the ESLint formatting & fixes PR to main
- merge this branch into any existing or stale branches to run the formatting prior to merging main into it.
  - this will avoid any merge conflicts from formatting changes

**Comment by odama626** [comment]
https://github.com/FlatbreadLabs/flatbread/pull/89

only 4 errors remain, and its around types
```/home/asparks/git/flatbread/packages/transformer-markdown/src/types.ts
  29:33  error  Don't use `object` as a type. The `object` type is currently hard to use ([see this issue](https://github.com/microsoft/TypeScript/issues/21732)).
Consider using `Record<string, unknown>` instead, as it allows you to more easily inspect and use the keys  @typescript-eslint/ban-types
  30:26  error  Don't use `object` as a type. The `object` type is currently hard to use ([see this issue](https://github.com/microsoft/TypeScript/issues/21732)).
Consider using `Record<string, unknown>` instead, as it allows you to more easily inspect and use the keys  @typescript-eslint/ban-types
  32:25  error  Don't use `object` as a type. The `object` type is currently hard to use ([see this issue](https://github.com/microsoft/TypeScript/issues/21732)).
Consider using `Record<string, unknown>` instead, as it allows you to more easily inspect and use the keys  @typescript-eslint/ban-types

✖ 97 problems (4 errors, 93 warnings)```

**Comment by tonyketcham** [comment]
Nice one! Excited for this since it'll keep us in line & up our code standards

**Comment by odama626** [comment]
can we get this in? it's non-breaking, just  really looking forward having pretty-quick

**Comment by odama626** [comment]
it's non breaking because lint:eslint isn't used by lint currently

**Review by tonyketcham — APPROVED** [review]

**Comment by tonyketcham** [comment]
Yup - sorry for the delay on approving this one!

**Pull request merged**
